version: '3.1'
services:
  microservice:
    container_name: auth_microservice_container
    build:
      context: .
    image: auth_microservice_image
    ports:
      - 10001:10001
    depends_on:
      - database
  database:
    image: cassandra
    container_name: auth_db
    ports:
      - 9042:9042